apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom-scheduler
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      schedulerName: custom-scheduler  # Specify our custom scheduler
      containers:
      - name: nginx
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
