apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-scheduler
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: custom-scheduler
        pluginConfig:
        - name: CustomSchedulingPlugin
          args:
            storageConfig:
              configMapName: "local-path-config"
              configMapNamespace: "kube-system"
              configKey: "config.json"
        plugins:
          # QueueSort插件
          # queueSort:
          #   enabled:
          #     - name: PrioritySort
          # PreFilter插件
          preFilter:
            enabled:
              # - name: NodeResourcesFit
              # - name: NodePorts
              # - name: NodeAffinity
              # - name: NodeName
              - name: CustomSchedulingPlugin
          # Filter插件
          filter:
            enabled:
              # - name: NodeUnschedulable
              # - name: NodeName
              # - name: NodePorts
              # - name: NodeAffinity
              # - name: NodeResourcesFit
              - name: CustomSchedulingPlugin
          # PostFilter插件
          postFilter:
            enabled:
              - name: DefaultPreemption
          # PreScore插件
          preScore:
            enabled: []
              # - name: NodeAffinity
              # - name: NodeResourcesFit
              # - name: CustomSchedulingPlugin
          # Score插件
          score:
            enabled:
              # - name: NodeResourcesBalancedAllocation
              #   weight: 1
              # - name: NodeResourcesFit
              #   weight: 1
              # - name: NodeAffinity
              #   weight: 1
              - name: CustomSchedulingPlugin
                weight: 1
          # Reserve插件
          reserve:
            enabled:
              - name: CustomSchedulingPlugin
          # Permit插件
          permit:
            enabled: []
          # PreBind插件
          preBind:
            enabled: []
          # Bind插件
          bind:
            enabled: []
              # - name: DefaultBinder
          # PostBind插件
          postBind:
            enabled: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-scheduler
rules:
# Core API permissions
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["create", "get", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["bindings", "pods/binding"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["patch", "update"]
- apiGroups: [""]
  resources: ["replicationcontrollers", "services", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

# Apps API permissions
- apiGroups: ["apps"]
  resources: ["statefulsets", "replicasets", "deployments"]
  verbs: ["get", "list", "watch"]

# Storage API permissions
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses", "csinodes", "csidrivers", "csistoragecapacities"]
  verbs: ["get", "list", "watch"]

# Policy API permissions
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch"]

# Scheduling API permissions
- apiGroups: ["scheduling.k8s.io"]
  resources: ["priorityclasses"]
  verbs: ["get", "list", "watch"]

# Node scheduling permissions
- apiGroups: [""]
  resources: ["nodes/status"]
  verbs: ["get", "patch", "update"]

# Resource coordination permissions
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "get", "list", "update"]

# Custom scheduler specific permissions
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-scheduler
subjects:
- kind: ServiceAccount
  name: custom-scheduler
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
  namespace: kube-system
  labels:
    app: custom-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler
  template:
    metadata:
      labels:
        app: custom-scheduler
    spec:
      serviceAccountName: custom-scheduler
      containers:
      - name: custom-scheduler
        image: deeplythink/custom-scheduler:latest
        imagePullPolicy: Always
        args:
        - --config=/etc/kubernetes/scheduler-config.yaml
        - --v=4  # 增加日志级别以便调试
        - --leader-elect=false  # 单实例模式，禁用选主
        volumeMounts:
        - name: scheduler-config
          mountPath: /etc/kubernetes/scheduler-config.yaml
          subPath: scheduler-config.yaml
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config
